name: Jason Laster
markdown: redcarpet
highlighter: rouge
description: This blog is a home for my technical thoughts.
url: http://jasonlaster.github.io/
syntax-highlighting:
  enabled : true
  css: syntax.css
